# Generated by Django 4.2.1 on 2023-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_address_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='details',
        ),
    ]
